### ISSUE TITLE
c or cpp call go bytes string strcov api 

### ISSUE THREAD

**Issue by ddkwork** [spyzhov/golang-shared#6]
how to use c or cpp call go bytes string strcov api? If you have a free time,please  make a  example,thank you my teacher.i want to use go api in windows driver code.

**Comment by spyzhov** [comment]
Hi! 

First of all, I should ask you NOT to do it. [cppreference.com](https://en.cppreference.com/w/cpp) has a lot of examples of how to do it in the `C` way. Example: [atoi](https://www.cplusplus.com/reference/cstdlib/atoi/)

if you really wanted to do something like this, you can check `GetImageSize` function from [library/main.go#L21](https://github.com/spyzhov/golang-shared/blob/master/library/main.go#L21) and how is it used in the `C` extension for `PHP7.3` in  `int print_image_size(char *path)` function [php-7.3/extension/example.c#L11](https://github.com/spyzhov/golang-shared/blob/master/php-7.3/extension/example.c#L11). So you'll be able to use the same approach.

**Comment by ddkwork** [comment]
> Hi!
> 
> First of all, I should ask you NOT to do it. [cppreference.com](https://en.cppreference.com/w/cpp) has a lot of examples of how to do it in the `C` way. Example: [atoi](https://www.cplusplus.com/reference/cstdlib/atoi/)
> 
> if you really wanted to do something like this, you can check `GetImageSize` function from [library/main.go#L21](https://github.com/spyzhov/golang-shared/blob/master/library/main.go#L21) and how is it used in the `C` extension for `PHP7.3` in `int print_image_size(char *path)` function [php-7.3/extension/example.c#L11](https://github.com/spyzhov/golang-shared/blob/master/php-7.3/extension/example.c#L11). So you'll be able to use the same approach.

Tank you
